# Generated by Django 5.0.7 on 2024-07-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu_name', models.CharField(max_length=100)),
                ('cpu_usage', models.FloatField()),
                ('gpu_name', models.CharField(max_length=100)),
                ('gpu_usage', models.FloatField()),
                ('func_description', models.TextField()),
                ('func_usage_cmd', models.TextField()),
                ('func_usage_params', models.TextField()),
            ],
        ),
    ]
